# Configuration for Label Actions - https://github.com/dessant/label-actions

# Specify actions for issues and pull requests
actions:
  "SUPPORT: Check Version":
    comment: >
      Check the latest version first.
    lock: false
    close: false
    lockReason: false
  "SUPPORT: Can't Reproduce":
    comment: >
      I have not managed to reproduce this issue.
    lock: false
    close: false
    lockReason: false

# Limit to only `issues` or `pulls`
only: issues

# Repository to extend settings from
# _extends: repo
